//{
//        "message": "List of the Applicants",
//        "object": [
//        {
//        "id": 1,
//        "firstName": "Ashish",
//        "lastName": "Tayade",
//        "mailID": "ashish@gmail.com",
//        "education": "nursey fail",
//        "mobileNo": "8789998859",
//        "alternateNo": "7865432349",
//        "fatherName": "Dnyaneshwar",
//        "motherName": "Sangita",
//        "dob": "11/05/1999",
//        "address": "At.potli tq.nandura",
//        "state": "Maharashtra",
//        "pinCode": "443404",
//        "category": "OBC",
//        "maritalStatus": "Unmarried",
//        "religion": "HIndu",
//        "citizenOfIndia": "yes",
//        "anyDisability": "no"
//        },
//        {
//        "id": 2,
//        "firstName": "Sagar",
//        "lastName": "Ubale",
//        "mailID": "sagar@gmail.com",
//        "education": " BE Computer",
//        "mobileNo": "8523697416",
//        "alternateNo": "9863524175",
//        "fatherName": "Tukaram",
//        "motherName": "Lela",
//        "dob": "11/05/1999",
//        "address": "Baramati",
//        "state": "Maharashtra",
//        "pinCode": "443404",
//        "category": "OBC",
//        "maritalStatus": "Unmarried",
//        "religion": "HIndu",
//        "citizenOfIndia": "yes",
//        "anyDisability": "no"
//        },
//        {
//        "id": 3,
//        "firstName": "Gitesh",
//        "lastName": "Darbastwar",
//        "mailID": "gtesh@gmail.com",
//        "education": " BE Computer",
//        "mobileNo": "8523697416",
//        "alternateNo": "9863524175",
//        "fatherName": "Tukaram",
//        "motherName": "Lela",
//        "dob": "11/05/1999",
//        "address": "Baramati",
//        "state": "Maharashtra",
//        "pinCode": "443404",
//        "category": "OBC",
//        "maritalStatus": "Unmarried",
//        "religion": "HIndu",
//        "citizenOfIndia": "yes",
//        "anyDisability": "no"
//        }
//        ],
//        "hasError": false
//        }